env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - next/core-web-vitals
  - plugin:@next/next/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module

plugins:
  - react
  - react-hooks

settings:
  react:
    version: detect

rules:
  indent:
    - error
    - 2

  linebreak-style:
    - error
    - unix

  quotes:
    - error
    - single

  semi:
    - error
    - never

  eqeqeq:
    - error
    - always
    - null: ignore

  space-before-blocks: error

  max-len:
    - error
    - code: 100

  'react/react-in-jsx-scope': off
