import Head from 'next/head'

import styles from '../styles/Home.module.scss'

const Home = () => {
  return (
    <div className={styles.Container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta content="text/html; charset=UTF-8" httpEquiv="Content-Type" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="format-detection" content="telephone=no" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.Main}>
        Hello, world!
      </main>
    </div>
  )
}

export default Home
